# configuration for correctly serving Angular apps with client-side routing
# without it, the Angular app will not work correctly when refreshing the page or navigating directly to a URL
server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    error_page 404 /index.html;
}
