# Workflow name
name: Continuous Deployment

# This allows manual start of the pipeline as needed.
on:
  workflow_dispatch:
  push:
    branches:
      - develop

# The list of jobs to run
jobs:
  backup_s3:
    runs-on: ubuntu-latest
    name: Backup S3 Content
    steps:
      - name: Configure AWS credentials for backup
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.REGION }}
      - name: Create S3 backup
        run: |
          DATE=$(date +%Y/%m/%d)
          aws s3 cp s3://my-proj-fe-dev/ s3://my-proj-fe-dev/BU/$DATE/ --recursive --exclude "BU/*"
  build_and_deploy_job:
    needs: backup_s3
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:

      # 1. Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.REGION }}

      # 2. Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: develop

      # 3. Setup Node
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20.11.1'

      # 4. Setup Cache
      - name: Setup Cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # 5. Build Angular
      - name: Build Angular Application
        run: |
          ls
          npm install -g @angular/cli
          npm install
          ng build

      # 6. Copy to S3 bucket.
      - name: Copy to S3 Bucket
        run: |
          aws s3 cp ./dist/angular-frontend-project/browser/ s3://my-proj-fe-dev/ --recursive --acl public-read
