name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - develop
      - master
      - feature/email-filter

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.3
        env:
          QODANA_TOKEN: ${{ eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJvcmdhbml6YXRpb24iOiJwNU53TSIsInByb2plY3QiOiIzd1JFZyIsInRva2VuIjoicFEwT2EifQ.WRaFqgknxlnYoYan38LvYZiRw36-dkSTOPHqV1oSbP0 }}